
package com.btdx.ldcj.jjxx.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "QueryPortType", targetNamespace = "http://ws.jjxx.ldcj.btdx.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QueryPortType {


    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "queryJQXX_ZFJLY")
    @WebResult(name = "out", targetNamespace = "http://ws.jjxx.ldcj.btdx.com")
    @RequestWrapper(localName = "queryJQXX_ZFJLY", targetNamespace = "http://ws.jjxx.ldcj.btdx.com", className = "com.btdx.ldcj.jjxx.ws.QueryJQXXZFJLY")
    @ResponseWrapper(localName = "queryJQXX_ZFJLYResponse", targetNamespace = "http://ws.jjxx.ldcj.btdx.com", className = "com.btdx.ldcj.jjxx.ws.QueryJQXXZFJLYResponse")
    public String queryJQXXZFJLY(
        @WebParam(name = "in0", targetNamespace = "http://ws.jjxx.ldcj.btdx.com")
        String in0);

}
