
package com.btdx.ldcj.jjxx.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Query", targetNamespace = "http://ws.jjxx.ldcj.btdx.com", wsdlLocation = "http://10.33.250.137:8090/JJXXWS/services/Query?wsdl")
public class Query
    extends Service
{

    private final static URL QUERY_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.btdx.ldcj.jjxx.ws.Query.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.btdx.ldcj.jjxx.ws.Query.class.getResource(".");
            url = new URL(baseUrl, "http://10.33.250.137:8090/JJXXWS/services/Query?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.33.250.137:8090/JJXXWS/services/Query?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        QUERY_WSDL_LOCATION = url;
    }

    public Query(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Query() {
        super(QUERY_WSDL_LOCATION, new QName("http://ws.jjxx.ldcj.btdx.com", "Query"));
    }

    /**
     * 
     * @return
     *     returns QueryPortType
     */
    @WebEndpoint(name = "QueryHttpPort")
    public QueryPortType getQueryHttpPort() {
        return super.getPort(new QName("http://ws.jjxx.ldcj.btdx.com", "QueryHttpPort"), QueryPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryPortType
     */
    @WebEndpoint(name = "QueryHttpPort")
    public QueryPortType getQueryHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.jjxx.ldcj.btdx.com", "QueryHttpPort"), QueryPortType.class, features);
    }

}
